---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - include_role:
        name: cluster
        tasks_from: sample_userdata
      tags:
        - never
        - sample

    - include_role:
        name: common
        tasks_from: auth_using_key_file

    - include_role:
        name: common
        tasks_from: enable_services
      vars:
        services:
            - cloudresourcemanager.googleapis.com
            - compute.googleapis.com
            - container.googleapis.com

    - include_role:
        name: service_account
        tasks_from: create
      vars:
        service_account_name: "{{ node_service_account }}"
        service_account_roles:
            - logging.logWriter
            - monitoring.metricWriter
            - storage.objectViewer

    - include_role:
        name: cluster
        tasks_from: create