---
- hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:

    - pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        extra_args: --user

  tasks:

    - include_role:
        name: common
        tasks_from: auth_using_key_file

    - include_role:
        name: create_cluster
