---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False

  pre_tasks:

    - include_role: 
        name: common
        tasks_from: ensure_user_configuration

    - include_role:
        name: common
        tasks_from: enable_services
      vars:
        services:
          - iam.googleapis.com

  tasks:

  - include_role:
      name: create_sa