---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False

  pre_tasks:

    - include_role:
        name: common
        tasks_from: get_project_id

  tasks:

  - include_role:
      name: create_sa