---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False

  vars:
    service_account_key_path: "{{ playbook_dir }}/keys/sa.json"

  pre_tasks:

    - include_role:
        name: common
        tasks_from: auth_using_key_file
    
    - pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        extra_args: --user

  tasks:

    - include_role:
        name: crete_cluster