---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - include_role: 
      name: common
      tasks_from: ensure_user_configuration
    tags:
      - always

  - block:
      - include_role:
          name: common
          tasks_from: enable_services
        vars:
          services:
            - iam.googleapis.com

      - include_role:
          name: service_account
          tasks_from: create
        vars:
          service_account_roles: 
            - editor
            - resourcemanager.projectIamAdmin

      - include_role:
          name: service_account
          tasks_from: create_key
    tags: 
      - key

  - include_role:
      name: project
      tasks_from: billing
    tags:
      - billing