---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False

  vars:
    key_file_path: ./keys/sa.json

  pre_tasks:
    - pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        extra_args: --user
      tags:
        - always

    - include_role:
        name: common
        tasks_from: ensure_key_file
      tags: 
        - clusters_create
  
  tasks:

    - include_role:
        name: init
      tags: init

