---
- name: discover project
  command: gcloud projects describe {{ project_id }}
  register: command_result
  ignore_errors: yes

- name: create project
  command: >
    gcloud projects create {{ project_id }} \
      --labels {{ labels }} \
      --organization {{ organization }} \
      --folder {{ folder }}
  when: command_result.rc > 0