#additional_zones: []
cluster_ipv4_cidr: '10.0.0.0/14'
#cluster_secondary_range_name: ''
#cluster_version: 1.9.7-gke.5
# create_subnetwork: 
#   name: ''
#   range: ''
disk_size: 100
enable_autorepair: True
enable_autoupgrade: False
enable_cloud_logging: True
enable_cloud_monitoring: True
# enable_ip_alias: False
# enable_kubernetes_alpha: False
# enable_legacy_authorization: False
# enable_network_policy: False
image_type: cos
labels: {}
local_ssd_count: 0
machine_type: n1-standard-1
maintenance_window: ''
#max_nodes_per_pool: 1000
#min_cpu_platform: ''
network: default
node_labels: {}
node_locations:
#node_taints: []
#node_version: ''
num_nodes: 3
preemptible: False
#services_ipv4_cidr: ''
#services_secondary_range_name: ''
subnetwork: ''
tags: []
zone: us-central-1a

addons:
  http_load_balancing:
    enable: True
  horizontal_pod_autoscaling:
    enable: True
  kubernetes_dashboard:
    enable: False

node_pool_autoscalling:
  enable: False
  max_nodes: 3
  min_nodes: 3

# master_authorized_networks:
#   enable: False
#   networks: [] 

basic_auth:
  enable: True
  username: admin
  password: ''

node_service_account: ''

scopes:
  - gke-default