---
- name: service to enable
  debug: var=services
  tags: always

- name: list enabled services
  command: >
    gcloud services list --format json
  register: command_result
  tags: always

- fail:
    msg: "Enable Service Management API via Google Cloud Console first."
  when: command_result.rc > 0
  tags: always

- set_fact:
    enabled_services: "{{ command_result.stdout | from_json | map(attribute='serviceName') | list }}"
  tags: always

- name: enabled services
  debug: var=enabled_services  
  tags: always

- name: enable additional services
  command: >
    gcloud services enable {{ item }}
  loop: "{{ services }}"
  when: item not in enabled_services
  tags: always