---
- name: ensure user account selected (not service)
  command: >
    gcloud config get-value core/account
  register: command_result
  tags: always
  
- fail:
    msg: "Please run 'glocud init' or 'gcloud config configrations activate CONFIGURATION' to choose initialized configuration."
  when: command_result.stdout is search('.iam.gserviceaccount.com')
  tags: always

- name: get project_id from active confguration
  command: gcloud config get-value core/project
  register: command_result
  tags: always

- fail:
    msg: "Plese run 'gcloud init' to initialize the project."
  when: command_result.stderr is search('(unset)')
  tags: always

- set_fact:
    project_id: "{{ command_result.stdout }}"
  tags: always